spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/spring-boot-basic
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
#        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  level:
#    root: info
#    org.springframework: debug
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
